### ISSUE TITLE
RottenTomatoes script broken

### ISSUE THREAD

**Issue by CollinChaffin** [Ede123/userscripts#3] opened 2017-06-03 07:01 UTC
Your script is not using a proper API key and results in this error being returned on every attempted RT icon add:

"Response":"False","Error":"No API key provided."}

Suggest you perhaps change your approach to be similar to others doing it and instead of performing the actual lookup of the title which requires an API key, use this instead:

http://www.rottentomatoes.com/search/?search={{PARAM}}&sitesearch=rt

And simply use the actual lookup string as the A HREF and leave it to the user click action to then manually perform the lookup, which then does NOT require the API key because it's not an automated call.

EDIT:  I missed that your last commit moved to omdb which is actually what has now broken.  I have simply forced a rollback to the last version before you made that commit but unfortunately, that is now broken too because that API key that was embedded I seem to be getting this returned which of course is HTML not valid JSON so the code blows up:

<h1>Developer Inactive</h1>

**Comment by Ede123** [comment] 2017-06-03 09:05
Thanks for the report. As you noted, Rotten Tomatoes locked their API a long time ago for most developers (I could not even get an API key if I wanted) and OMDb API had to lock their public API due to extreme traffic and pressure from their provider...

I'm afraid I don't know of a way to really fix the script right now:
* I could resort to a simple title search on RottenTomatoes, but that's far from optimal and the exact thing I wanted to improve upon from the start with my script.
* I could pay for OMDb API access (which is unlikely to be honest - I chose OMDb API because it was free!) but as the key is included in the code more or less encrypted I don't know if this is would even be allowed (what I did with the RT API was most likely not).

I'm not sure I understood you suggestion: What would `{{PARAM}}` be in your example? The movie title (i.e. the first option above) or do you know of a way to search by IMDb id?

Right know I'm still hoping Brian Fritz will eventually be able to open up the API to the public again. Previous communication indicated the whole Patreon-thing was intended to collect money for a paid plan, so he could host his own server, but the last message wasn't so clear anymore I'm afraid...

**Comment by Ede123** [comment] 2018-04-22 13:15
Fixed in 0ae810bbf0f01e3f4be7ac12560f8f7201d98724.

OMDb API offers free API keys now. Unfortunately they are limited to 1000 requests per day, but maybe it's sufficient, let's see...

**Closed by Ede123** 2018-04-22 13:15 UTC
